"""Fiat-Shamir transcript, Pedersen commitments, Schnorr identification & signatures.

Maps to paper Section III (Background/Preliminaries):
 - Pedersen commitment: C = v*G + r*H  (perfectly hiding, computationally binding,
   additively homomorphic).  [Pedersen, CRYPTO '91]
 - Schnorr Sigma protocol + Fiat-Shamir transform for non-interactivity.
   [Schnorr, J. Cryptology 1991; Fiat-Shamir, CRYPTO '86]
"""
from __future__ import annotations
import hashlib
import secrets
from dataclasses import dataclass

from .curve import G, H, N, Point


# ---------------------------------------------------------------- transcript
class Transcript:
    """Fiat-Shamir transcript with domain separation and length framing.

    Every absorbed item is framed as  len(label)|label|len(data)|data  so the
    byte stream is unambiguous (prevents transcript-splicing malleability).
    """

    def __init__(self, domain: bytes):
        self._h = hashlib.sha256()
        self.absorb(b"domain", domain)

    def absorb(self, label: bytes, data: bytes) -> None:
        for chunk in (label, data):
            self._h.update(len(chunk).to_bytes(8, "big"))
            self._h.update(chunk)

    def absorb_point(self, label: bytes, pt: Point) -> None:
        self.absorb(label, pt.compress())

    def absorb_int(self, label: bytes, x: int) -> None:
        self.absorb(label, x.to_bytes(32, "big"))

    def challenge(self, label: bytes) -> int:
        h = self._h.copy()
        h.update(b"||challenge||" + label)
        return int.from_bytes(h.digest(), "big") % N


# ---------------------------------------------------------------- pedersen
def commit(value: int, blinding: int) -> Point:
    """C = value*G + blinding*H"""
    return (value % N) * G + (blinding % N) * H


def rand_scalar() -> int:
    return secrets.randbelow(N - 1) + 1


# ---------------------------------------------------------------- schnorr
@dataclass
class SchnorrProof:
    commitment: Point  # a = w*Base
    response: int      # z = w + e*x


def schnorr_prove(secret: int, base: Point, public: Point, ts: Transcript) -> SchnorrProof:
    """NIZK PoK{ x : public = x*base } via Fiat-Shamir."""
    w = rand_scalar()
    a = w * base
    ts.absorb_point(b"schnorr/base", base)
    ts.absorb_point(b"schnorr/pub", public)
    ts.absorb_point(b"schnorr/a", a)
    e = ts.challenge(b"schnorr/e")
    z = (w + e * secret) % N
    return SchnorrProof(a, z)


def schnorr_verify(proof: SchnorrProof, base: Point, public: Point, ts: Transcript) -> bool:
    ts.absorb_point(b"schnorr/base", base)
    ts.absorb_point(b"schnorr/pub", public)
    ts.absorb_point(b"schnorr/a", proof.commitment)
    e = ts.challenge(b"schnorr/e")
    return proof.response * base == proof.commitment + e * public


# Schnorr signatures (used to sign predicate-registry entries: governance keys)
def sign(secret: int, msg: bytes) -> tuple[int, int]:
    pub = secret * G
    w = rand_scalar()
    a = w * G
    e = int.from_bytes(
        hashlib.sha256(b"zkgw/sig/v1|" + a.compress() + pub.compress() + msg).digest(), "big"
    ) % N
    return e, (w + e * secret) % N


def sig_verify(pub: Point, msg: bytes, sig: tuple[int, int]) -> bool:
    e, z = sig
    a = z * G - e * pub
    e2 = int.from_bytes(
        hashlib.sha256(b"zkgw/sig/v1|" + a.compress() + pub.compress() + msg).digest(), "big"
    ) % N
    return e == e2


# ------------------------------------------------- worked example (Appendix)
def schnorr_worked_example() -> str:
    """Tiny-number Schnorr identification transcript for the paper's appendix.

    Group: Z_23^* subgroup of order 11 generated by g=2  (2^11 = 2048 = 1 mod 23).
    Secret x=7, public y = g^x = 2^7 mod 23.
    """
    p, q, g = 23, 11, 2
    x = 7
    y = pow(g, x, p)
    w = 3                      # prover nonce (fixed for reproducibility)
    a = pow(g, w, p)
    e = 5                      # verifier challenge (interactive round)
    z = (w + e * x) % q
    lhs = pow(g, z, p)
    rhs = (a * pow(y, e, p)) % p
    lines = [
        "Schnorr identification, worked example (p=23, q=11, g=2):",
        f"  secret x = {x};  public y = g^x mod p = {y}",
        f"  1. Prover picks w = {w}, sends a = g^w mod p = {a}",
        f"  2. Verifier sends random challenge e = {e}",
        f"  3. Prover sends z = w + e*x mod q = {z}",
        f"  4. Verifier checks g^z == a * y^e  (mod p):  {lhs} == {rhs}  -> {lhs == rhs}",
        "  Zero-knowledge: (a, e, z) can be simulated without x by sampling z, e",
        "  first and computing a = g^z * y^-e; Fiat-Shamir sets e = Hash(transcript).",
    ]
    assert lhs == rhs
    return "\n".join(lines)
