apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zkgw-gateway
  labels:
    app.kubernetes.io/name: zkgw-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zkgw-gateway
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: {{ .Values.gateway.service.port }}
